name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: library_data_v1
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    # Step 1: Checkout code
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Adjust Python version as needed

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Set up environment variables
    - name: Set environment variables
      run: |
        echo "DATABASE_URL=postgres://github:github@localhost:5432/github_ci" >> $GITHUB_ENV
        echo "DEBUG=True" >> $GITHUB_ENV

    # Step 5: Run database migrations
    - name: Run migrations
      run: |
        python manage.py migrate

    # Step 6: Run tests
    - name: Run tests
      run: |
        python manage.py test
